import Head from "next/head";
import { ReactNode } from "react";

interface MainLayoutProps {
    pageTitle: string;
    children: ReactNode;
}

function MainLayout({ pageTitle, children }: MainLayoutProps) {
    const title = `Aurora | ${pageTitle}`;
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta
                    name="viewport"
                    content="minimum-scale=1, initial-scale=1, width=device-width"
                />
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>{children}</main>
        </>
    );
}

export default MainLayout;
