import Head from "next/head";

interface HeadProps {
    title: string;
}

const NextHead = ({ title }: HeadProps) => (
    <Head>
        <title>{title}</title>
        <meta
            name="viewport"
            content="minimum-scale=1, initial-scale=1, width=device-width"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
);

export default NextHead;
