import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
   return (
      <>
         <Head>
            <title>Auroroa</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className={inter.className}>
            <div className="text-red-500">hi</div>
         </main>
      </>
   )
}
